global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: /metrics

  - job_name: 'discovery-service'
    static_configs:
      - targets: ['discovery-service:8001']
    metrics_path: /metrics

  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:8002']
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']